### ISSUE TITLE
use-first-last rule not working properly

### ISSUE THREAD

**Issue by jlin412** [alecxe/eslint-plugin-protractor#50]
I am using cucumber with protractor.  When I apply use-first-last rule, I am getting the following error msg:

```
Warning: Cannot read property 'value' of undefined Use --force to continue.
```

I am not sure what is happening

**Comment by alecxe** [comment]
@jlin412 ah, sorry for that, might be something I missed during testing. Could you run eslint with `--debug` flag and identify in which file and on what line does it fail so miserably? Thanks.

Meanwhile I'll try to see if I can locate that problem myself.

**Comment by jlin412** [comment]
Ok, I run eslint --debug but no extra information is output.  I have about
thousand files.  It will be difficult to tell which one :(
Any suggestion?

**Comment by alecxe** [comment]
@jlin412 there should be a lot of lines yeah, multiple lines per single processed file. But, since this fails and stops the eslint run, the file containing the problem should be the last one being processed. Please try to inspect it and see where the `.get()` methods are used there. Or, if it is not a secret, post the contents of the file here. Thanks!

**Comment by alecxe** [comment]
I am pretty sure I know where to apply a fix, but I'd rather first understand what kind of code can cause the problem before fixing the bug, instead of blindly applying a fix. At this point, I have not figured that out. Thanks.

**Comment by jlin412** [comment]
I still have no luck in getting more output in --debug.  I tried --verbose as well but no avail.
How about this?  If you create a new branch, I could run it with that branch to see if it is working with your new fix.

**Comment by alecxe** [comment]
@jlin412 I am just not willing to blindly apply the fix and curious what code causes the problem (will do that when we run out of options). Okay, could you please search for `.get(` in your test codebase and paste here the results? Thank you!

**Comment by jlin412** [comment]
@alecxe I am not asking you to apply the fix blindly.  Just wondering if you can create a new branch with the fix or just create a PR that I copy and paste so I can verify it for you.
I search .get instances.  There are in the order of thousands so it is not very helpful in debugging.

**Comment by alecxe** [comment]
@jlin412 gotcha, I've applied a fix (866a0413f057b3062c668e9ebd8a083d179f1a08). Please install the latest plugin version (1.27.1) from npm and see if it made any difference. Thank you!

**Comment by jlin412** [comment]
@alecxe I tried and it did work. Good job in figuring out blindly 👍   What was wrong with it?

**Comment by alecxe** [comment]
@jlin412 glad to see it works for you. Yeah, this is one of those times when you know the process, the result and the solution, but you don't know what exactly caused the result :) Thanks for the report.
