### ISSUE TITLE
keyword import is reserved

### ISSUE THREAD

**Issue by shavo007** [alecxe/eslint-plugin-protractor#61]
Hi,

I just recently added this module for my protractor tests.

I installed es-lint and eslint-plugin-protractor.
`
"eslint": "^3.11.1",
    "eslint-plugin-protractor": "^1.30.0",
`

I am using ATOM as my IDE. I installed the package linter-eslint.

The config in eslintrc is 

`
{
  "plugins": [
    "protractor"
  ],
  "extends": "plugin:protractor/recommended"
}
`

When i saved my spec file I get this error. My specs are defined using es6. So not sure why this is an error.

Thanks,
Shane.

**Comment by alecxe** [comment]
@shavo007 thanks for using the library (at least trying :)). This looks like a generic ESLint problem, not specific to the plugin, but let's see what can help. 

This looks relevant: 

* https://github.com/yannickcr/eslint-plugin-react/issues/447#issuecomment-184617282
 * http://stackoverflow.com/questions/36002226/parsin-error-the-keyword-import-is-reserved-sublimelinter-contrib-eslint
 * https://discuss.atom.io/t/eslint-parsing-error-keyword-import-is-reserved/31704.

Please see if any of these links help.

**Comment by shavo007** [comment]
Awesome.

I installed  babel-eslint and in the config file added the entry:


"parser": "babel-eslint"


Now i see all the nice warnings i have!!! ;-)

**Comment by alecxe** [comment]
@shavo007 thanks! I would really appreciate the feedback, feel free to create feature requests or request improvements or send the pull requests. 

Most of the implemented or planned ideas are coming from the styleguide, personal experience or undergoing work projects and sometimes from stackoverflow real world use cases - I wish I had more real-world usages of the plugin and ideas to develop new rules to check the Protractor tests.

**Comment by shavo007** [comment]
no worries @alecxe happy to contribute
