### ISSUE TITLE
Support for eslint-plugin-protractor in cliptor - protractor's interactive cli

### ISSUE THREAD

**Issue by igniteram** [alecxe/eslint-plugin-protractor#85]
This is not an issue, please mark it with the question tag

Would like to include eslint-plugin-protractor in [cliptor](https://github.com/igniteram/Cliptor.js) as the default linter for writing protractor scripts, currently this plugin should be added to the config file. Just wanted to know will this change in future and is this still an active project?

**Comment by alecxe** [comment]
@igniteram yes, this is still active, there are some features/issues planned to be included in the version 2. But, the configuration itself would stay the same as long as eslint itself keeps it this way :) 

By the way, nice idea to make protractor config generation utility! 👍

**Comment by igniteram** [comment]
Great, thanks! do give it a try, need to add additional features & extensive tests. Would include in coming releases. To know more about its tech stack and modules you can refer this [medium post](https://medium.com/@igniteram/cliptor-protractors-interactive-cli-33b04937dafc) . @cnishina is also throwing in his expertise!

**Comment by igniteram** [comment]
@alecxe `eslint-plugin-protractor` has been added with this PR https://github.com/igniteram/protractor-cli/pull/13, lot of new features have been added and the name changed to protractor-cli :) I will try to add some cucumber rules to this linter 👍
