### ISSUE TITLE
Globals not loaded automatically.

### ISSUE THREAD

**Issue by tregusti** [alecxe/eslint-plugin-protractor#88]
The globals config added in #29 is not used automatically. I get lots of warnings about `browser`, `by` and such.

I had to get and expose it myself:

```js
const globals = require('eslint-plugin-protractor').configs.recommended.globals;

module.exports = {
    plugins: [
        'protractor'
    ],
    globals: { ...globals }
};
```

Maybe expose it as an environment as per the docs: https://eslint.org/docs/developer-guide/working-with-plugins#environments-in-plugins?

I'm using
- `eslint` 4.19.1
- `eslint-plugin-protractor` 1.40.2

**Comment by alecxe** [comment]
@tregusti thanks for the request and for using the plugin!

It's been a while I've personally used `ESLint` but I think I got what you meant. Please see if this solves your problem: e1db5e89f8e62342fff8b4a22a71db8e51cc1fdf. Thanks!

**Comment by alecxe** [comment]
It's now a part of 1.41.0 btw.

**Comment by tregusti** [comment]
It works just fine. Thank you!
